### PR TITLE
fix: MD001/heading-increment/header-increment

### PR DESCRIPTION
**Pull request by nschonni**
Heading levels should only increment by one level at a time.
Disable for pages with "tabs" since they currenlty us H1s

### CODE REVIEW

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by nschonni** [comment]
@conceptdev there are a bit more (probably a second one of this size) so the .markdownlint.json doesn't enable this yet. Figured this was a big enough batch to look at one time

**Comment by conceptdev** [comment]
Thanks, it's definitely helpful and easier to do in smaller chunks.

**Review by conceptdev — APPROVED** [review]
the **conceptual tabs** syntax is definitely problematic for this rule! Thanks for the updates/disables.

**Comment by conceptdev** [comment]
#sign-off

**Pull request merged**
