### PR TITLE
Update right-to-left.md

### PR DESCRIPTION
**Pull request by Elashi**
My app only supports Arabic language and I wanted it to display it in right-to-left direction, regardless of device settings.  This might be a life saving tip.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Elashi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@conceptdev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by conceptdev** [comment]
Thanks for the contribution @Elashi, I updated the formatting a bit to match our style. The doc author will review next week.

**Comment by PRMerger13** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks @Elashi

**Pull request merged**
