### PR TITLE
Device-display UIKitThreadAccessException warning

### PR DESCRIPTION
**Pull request by framinosona**

### CODE REVIEW

**Comment by framinosona** [comment]
Following @craylward : https://github.com/xamarin/Essentials/issues/463

**Comment by conceptdev** [comment]
Thanks for the PR @Hammerhead73 - we'll review asap.

**Comment by jamesmontemagno** [comment]
I actually think this is a bug for the library actually that needs to be looked at. I would not put this here, i would put it in "Platform Differences" for instance

I don't like showing an example of it because it isn't needed on other platforms and may break how people are using it.

**Comment by conceptdev** [comment]
@Hammerhead73 as explained above, since this is really an iOS-specific change (the tip mentions `UIKit.UIKitThreadAccessException `), it would be better presented as platform-specific guidance. 

If you'd like to propose a new PR, you could look at https://github.com/MicrosoftDocs/xamarin-docs/pull/930/files for an idea of how the **Platform differences** section is usually formatted.

Thanks!

**Pull request closed without merging**
