### PR TITLE
fix: MD045/no-alt-text

### PR DESCRIPTION
**Pull request by nschonni**
Images should have alternate text.
Many had it in the "title" position instead of alt-text

### CODE REVIEW

**Comment by conceptdev** [comment]
Hey @nschonni - have you already measured many files are affected by this across the entire repo? It can affect accessibility and as-such is on our backlog to address as well.

**Comment by nschonni** [comment]
I think probably quite a few more. You can check locally but removing the MD045 rule from the markdownlint.json and then `npm i -g markdownlint-cli` and run the linting by running `markdownlint "**/*.md"` at the root of the repo

**Comment by conceptdev** [comment]
Yeah, I suspect a lot. In our old publishing system we dealt with these differently (to ensure accessibility), but the new renderer does not. Let me check the impact - I am wondering if it will be easier for us to update internally, 'all at once', rather than chunked commits.

**Comment by nschonni** [comment]
Yeah, this was just manual, but you could probably figure out a good regex. 1 for the plain title-only version, and the second for the lightbox one. I think that is probably 99% of them and then the commandline can flag the last few

**Review by conceptdev — APPROVED** [review]
These look good, thanks. Will take a look across the whole repo...

**Comment by nschonni** [comment]
I'll see if I can figure out a regex if you don't get to it first

**Comment by nschonni** [comment]
Did figure out the regex, but did it on the old branch and am working through a bunch of merge conflicts.
The basic idea is
```
Find:!\[\]\((.*)\.png "(.*)"\)
Replace:![$2]($1.png)
```
And repeat for gif and jpg. There is also some manual fixing for the ones with multiple images on the same line

**Pull request merged**
