### PR TITLE
Updated Xamarin.Essentials: Share Multiple Files

### PR DESCRIPTION
**Pull request by dimonovdd**
Added information on sharing multiple files 

Linked [Issue](https://github.com/xamarin/Essentials/issues/1426) and [Pull Request](https://github.com/xamarin/Essentials/pull/1445)

### CODE REVIEW

**Comment by PRMerger16** [comment]
@dimonovdd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@jamesmontemagno Views?

**Comment by jamesmontemagno** [comment]
So, this needs to have a Preview tag on it and also wait for it to be merged and released in the nuget.

**Comment by PRMerger9** [comment]
@dimonovdd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dimonovdd** [comment]
@davidbritch @jamesmontemagno I think we can merge this
https://github.com/xamarin/Essentials/releases/tag/1.6.0-pre3

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
#sign-off

**Review by davidbritch — APPROVED** [review]

**Comment by PRMerger16** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
