### PR TITLE
added button control state list #hacktoberfest

### PR DESCRIPTION
**Pull request by logeshpalani33**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@logeshpalani98 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by logeshpalani33** [comment]
hacktoberfest pull request commit

**Comment by PRMerger14** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks @logeshpalani98

**Pull request merged**
