### PR TITLE
Update share.md

### PR DESCRIPTION
**Pull request by hatsunea**
Change to a valid default link destination

### CODE REVIEW

**Comment by PRMerger16** [comment]
@hatsunea : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jamesmontemagno** [comment]
the master branch is always shipping in the nuget and develop is just dev branch

**Comment by hatsunea** [comment]
I realized that the Master branch on github has been renamed to the main branch.
Therefore, the correct fix for the broken link is to put it in the main branch, not develop.

https://github.com/xamarin/Essentials/tree/master/Xamarin.Essentials/Share
↓
https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/Share

**Comment by PRMerger8** [comment]
@hatsunea : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jamesmontemagno** [comment]
Ah, I will do 1 huge PR for this as it effects all of the repos

**Comment by davidbritch** [comment]
Thanks for the PR @hatsunea but this has already been dealt with for all the Essentials docs by @jamesmontemagno 

Apologies for not getting to this PR sooner.

**Pull request closed without merging**
