### PR TITLE
Update Xamarin.Essentials support status

### PR DESCRIPTION
**Pull request by Happypig375**
https://github.com/xamarin/Essentials/blob/develop/Xamarin.Essentials/Battery/Battery.netstandard.tvos.cs

### CODE REVIEW

**Comment by PRMerger19** [comment]
@Happypig375 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Happypig375 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Happypig375 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Happypig375 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Happypig375** [comment]
Haha PRMergers

**Comment by Happypig375** [comment]
Fixes #2567

**Review by jamesmontemagno — APPROVED** [review]
Thanks!!!! It is a big grid :)

**Comment by jamesmontemagno** [comment]
#sign-off

**Pull request merged**
