### PR TITLE
Updating Broken Link for GridLayoutDemo

### PR DESCRIPTION
**Pull request by james-alt**
Updated the link for GridLayoutDemo as reported in #2182

### CODE REVIEW

**Comment by PRMerger18** [comment]
@james-alt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@conceptdev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by conceptdev — APPROVED** [review]
Thanks for finding & fixing!

**Comment by conceptdev** [comment]
#sign-off

**Pull request merged**
