### PR TITLE
Update geocoder.md

### PR DESCRIPTION
**Pull request by Nerves82**
Adding a note pointing to the Xamarin Essentials API for reference.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Nerves82 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Nerves82 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks for this @Nerves82

**Pull request merged**
