### PR TITLE
I added additional information about limitations placed on implicit broadcast  receivers on android API 26 and above

### PR DESCRIPTION
**Pull request by DamienDoumer**
The documentation did not contain tips on limitations placed on implicit broadcast receivers as from android 8. Reader might have difficulties listening to implicit broadcast receivers on these devices. I had this problem, and the link and the tip I added in this commit helped me resolve it.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@DamienDoumer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@conceptdev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by conceptdev — APPROVED** [review]
Thanks for the contribution @DamienDoumer!

**Comment by conceptdev** [comment]
#sign-off

**Pull request merged**
