### PR TITLE
Update map.md

### PR DESCRIPTION
**Pull request by ncarandini**
I've changed the `meta-data android:name` to `com.google.android.maps.v2.API_KEY` and changed the subsequent Note because is better to add more credential to the same key than to have two different API keys, one for DEBUG and one for RELEASE.

### CODE REVIEW

**Comment by conceptdev** [comment]
Thanks for the update @ncarandini - I'm gonna get an Android expert to review and approve.

**Comment by ncarandini** [comment]
Hi @conceptdev, maybe you can use the already accepted PR #448 that has the same info:
- about the `Note ` at the point 7 of [Obtaining the API Key](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key?tabs=vswin#obtaining-the-api-key)
- about the `meta-data android:name` at the end ([Adding the Key to Your Project](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key?tabs=vswin#adding-the-key-to-your-project))

**Comment by ncarandini** [comment]
@conceptdev no one available to review this? The other PR has been already merged, should be easy to review this one. Thanks in advance.

**Review by conceptdev — APPROVED** [review]
consistent with the PR accepted by the Android team https://github.com/MicrosoftDocs/xamarin-docs/pull/448/files

**Comment by conceptdev** [comment]
@ncarandini thanks for the PR (and your patience)!

**Pull request merged**
