### PR TITLE
Xamarin.Essentials: Initialization on iOS

### PR DESCRIPTION
**Pull request by dimonovdd**
Added information about initialization of Essentials on iOS

Linked  [Pull Request](https://github.com/xamarin/Essentials/pull/1846)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@dimonovdd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jamesmontemagno** [comment]
Will wait for this to go live and then push it out.

**Comment by dimonovdd** [comment]
@jamesmontemagno Hi. [Xamarin.Essentials](https://www.nuget.org/packages/Xamarin.Essentials) 1.7.1 was published

**Comment by jamesmontemagno** [comment]
Yay!!!

**Comment by jamesmontemagno** [comment]
#sign-off

**Review by jamesmontemagno — APPROVED** [review]

**Comment by dimonovdd** [comment]
@jamesmontemagno Is there something preventing us from merging it?

**Review by jamesmontemagno — APPROVED** [review]

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
#sign-off

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
hmmmmmnot sure why i can't merge.. @davidbritch

**Comment by davidbritch** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@davidbritch: I'm sorry - only the author of this article, @jamesmontemagno, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by davidbritch — APPROVED** [review]

**Comment by davidbritch** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@davidbritch: I'm sorry - only the author of this article, @jamesmontemagno, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
