### PR TITLE
fix: MD030/list-marker-space

### PR DESCRIPTION
**Pull request by nschonni**
Remove space after indented ordered lists

### CODE REVIEW

**Comment by conceptdev** [comment]
Almost 300 files! Going to need some time to review. In future, might be worth splitting into separate PRs, maybe by platform (xamarin/ios, xamarin/android, xamarin/xamarin-forms, etc).

**Comment by nschonni** [comment]
It was mostly find/replace. I can try and split it by area if you want

**Comment by conceptdev** [comment]
No no, this PR is fine. I hate "making work", so no need to re-do. GitHub's new "Viewed" tracking makes it a LOT easier with large PRs, but _in general_ smaller chunks are preferred. Either way appreciate your contributions!

**Comment by conceptdev** [comment]
replaced by rebase on https://github.com/MicrosoftDocs/xamarin-docs/pull/2026

**Pull request closed without merging**
