### PR TITLE
Update web-authenticator.md with changes required for changes required in Android 11 (API Level 30 - R)

### PR DESCRIPTION
**Pull request by MorneZaayman**
It relates to this issue: https://github.com/xamarin/Essentials/issues/1586

### CODE REVIEW

**Comment by PRMerger6** [comment]
@MorneZaayman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MorneZaayman** [comment]
It relates to this issue: https://github.com/xamarin/Essentials/issues/1586

**Comment by davidbritch** [comment]
@Redth @jamesmontemagno @mattleibow Is this ok to merge?

**Comment by Redth** [comment]
I'd like input from @mattleibow  .... These manifest attributes should be getting merged in automatically, so maybe some work needs to be done to see if that's not really the case and if so, why.

**Comment by jamesmontemagno** [comment]
It has to be added manually. We do the same for email/sms and such. I don't think there is an attribute yet from what I have seen. Although looking at the code I see  Intent.ActionView, but the docs do say to do what the PR says and that is similar to waht I have documented for Azure AD - https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs#L62
https://developers.google.com/web/android/custom-tabs/implementation-guide#how_can_i_check_whether_the_android_device_has_a_browser_that_supports_custom_tab

I can't update the PR, but please update it to our standard phrasing for this:

If your project's Target Android version is set to **Android 11 (R API 30)** you must update your Android Manifest with queries that are used with the new [package visibility requirements](https://developer.android.com/preview/privacy/package-visibility).

Open the **AndroidManifest.xml** file under the **Properties** folder and add the following inside of the **manifest** node:

```xml
<queries>
  <intent>
    <action android:name="android.support.customtabs.action.CustomTabsService" />
  </intent>
</queries>
```

**Comment by PRMerger13** [comment]
@MorneZaayman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jamesmontemagno — APPROVED** [review]

**Review by davidbritch — APPROVED** [review]
Thanks @MorneZaayman

**Pull request merged**
