### PR TITLE
Removing duplicate files causing git errors on mac, GitKraken

### PR DESCRIPTION
**Pull request by framinosona**
Deleted :
new-phone-dialer-android.w157.PNG
new-phone-dialer-ios.w157.PNG

Those files are unused

### CODE REVIEW

**Review by jzeferino — CHANGES_REQUESTED** [review]
I've found these files beeing used [here](https://github.com/MicrosoftDocs/xamarin-docs/blob/3645da3b5bd748fc33ee6ac7cb997a90b14a9151/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md).

**Comment by framinosona** [comment]
No no it's 
- new-phone-dialer-ios.w157.png and 
- new-phone-dialer-android.w157.png
that are used, but those .PNG duplicates that I want to remove make Gitkraken think there is an error and want to remove them.

**Comment by davidbritch** [comment]
Hi @Hammerhead73 

You're correct (.PNG aren't used, .png are used). I've just kicked off a build to check that removing the .PNGs don't cause any problems. Then I can hopefully accept the PR.

**Review by davidbritch — APPROVED** [review]
Nice catch, thanks!

**Comment by framinosona** [comment]
;) Happy to help !

**Pull request merged**
