### PR TITLE
Fixed an internal link in the Performance article (Android)

### PR DESCRIPTION
**Pull request by TimoSalomaki**
- The internal link to the row view reuse of the ListView article was missing.
- Added a missing comma

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Thanks!  However, the addition of the `#row-view-re-use` will not work until an anchor is added to the target. For example:

```
<a name="row-view-re-use" />

### Row View Re-Use
```

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Here goes ...

**Comment by TimoSalomaki** [comment]
Fingers crossed! Anyway, thanks for the comment. That was an oversight on my part as I didn't know about a new publishing system that could handle this case correctly.

**Comment by ghost** [comment]
It works! (Internally.) Just needs to propagate to the live site. Thanks again!

**Pull request merged**
