### PR TITLE
Added note on how to choose the C++ debugger, update VS2017

### PR DESCRIPTION
**Pull request by kzu**

### CODE REVIEW

**Comment by kzu** [comment]
Would be nice to add a screenshot, like the following:

image

but I've no idea what are the formatting requirements, so I'll leave it up to the docs team. /cc @conceptdev

**Review by ghost — APPROVED** [review]
Excellent addition!  I've tweaked it a bit for our style guide. We'll capture screenshots and add those separately.

**Comment by pwink53** [comment]
The debugger selection is the easy part.  Finding a "C++ **Dynamic Shared Library (Android)** project" is the trick here. That's the screen shot you need. (I'm still looking).

**Comment by ghost** [comment]
Actually, we have an [open issue](https://github.com/xamarin/documentation/issues/2407) to update this topic with a better C++ example than SanAngeles &ndash; I've included a note there to also add the necessary debugger selection screenshots.

**Comment by kzu** [comment]
@pwink53 it might be that you're missing the C++ Mobile workload entirely if you're not finding that project template:

image

With that, I see it as:

image

**Pull request merged**
