### PR TITLE
Update xamlc.md

### PR DESCRIPTION
**Pull request by hot33331**
Changed according to information from Stephane Delcroix on Feb 3rd.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@hot33331 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@hot33331 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks @hot33331

**Comment by PRMerger10** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
