### PR TITLE
Update hot-restart.md

### PR DESCRIPTION
**Pull request by mallibone**
Add description on how to enable Hot Restart in Visual Studio 16.5 Preview 3 and higher.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@mallibone : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
Can you take a look at this @jimmgarrido

**Comment by jimmgarrido** [comment]
Thank you for the contribution @mallibone! I've been working on updates to this doc internally as well where this change is noted, but it's taken longer to get ready for publishing. However, those changes should be live soon so I'm going to close this PR. I apologize for the confusion and I do appreciate the time you took to make this update!

**Comment by mallibone** [comment]
@jimmgarrido no worries 🙂

**Pull request closed without merging**
