### PR TITLE
Add information about http clear-text traffic

### PR DESCRIPTION
**Pull request by jamesmontemagno**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@jamesmontemagno : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks @jamesmontemagno

**Comment by PRMerger19** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]

**Pull request merged**
