### PR TITLE
Added missing "/" in closing tag

### PR DESCRIPTION
**Pull request by tentom**
Added missing "/" in closing MonoAndroidResourcePrefix tag in AndroidResources section.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@tentom : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks @tentom

**Comment by davidbritch** [comment]
Hi @tentom 

This file has changed significantly since you made your PR. The code that needs updating is now in build-items.md, rather than build-process.md. While I can fix this, you'll lose your contribution then.

There are two options:

1. You rebase your PR, delete your current change and update build-items.md.
1. I delete this PR and create one to fix it myself.

Let me know how you want to proceed.

**Comment by PRMerger10** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
