### PR TITLE
typo: PreferenceWidow -> PreferenceWindow

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Review by conceptdev — COMMENTED** [review]
whoops, thanks for spotting and fixing

**Review by conceptdev — APPROVED** [review]

**Comment by nschonni** [comment]
@conceptdev does anything need to happen to get these changes into the localization repos, or will that happen "automagically"?

**Comment by conceptdev** [comment]
It happens automatically, but not immediately. The localization workflow periodically picks up changes from the git log, determines if they need to be translated (eg. code blocks do not), and manages the actual translation (if required) and publishing to the localized repos/content.

**Comment by nschonni** [comment]
Thanks for explaining.
I'll assume these fixes will trickle down eventually, and won't do PRs for the localization repos with the same issues

**Comment by conceptdev** [comment]
Yes, that's the best bet. Contributions to the localized repos are optimized for feedback/udpates on the translation. Content changes are best done in the original source and propagated; less chance of any conflict resolution being required. Thanks for asking!

**Pull request merged**
