### PR TITLE
Use correct extension class name in XAML

### PR DESCRIPTION
**Pull request by Depechie**
The document shows code on how to create an extension that can be used in XAML to work with images embedded resources. But the XAML syntax is not using the correct extension class name, like the one created in the code snippet above.

This PR fixes that.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Depechie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
Hi @Depechie 

The existing code in the doc is identical to the code in the sample.

**Comment by Depechie** [comment]
Weird. I tried this sample in my own app and could not get the extension to show up in XAML if I did not change the name.

I did not check the sample ( sorry I missed that ).

**Comment by davidbritch** [comment]
@Depechie 

Thinking out loud. Were you using a release build? Wondering if it got linked out?

```
	// You exclude the 'Extension' suffix when using in Xaml markup
	[Preserve(AllMembers = true)]
	[ContentProperty (nameof(Source))]
	public class ImageResourceExtension : IMarkupExtension
```

**Comment by Depechie** [comment]
Not sure... sorry for the trouble. Can't recall the exact settings. So better to just close the PR.
Next time I will double check if there is a sample and what that code looks like.

**Pull request closed without merging**
