### PR TITLE
Update get-started-with-xaml.md

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Youssef1313 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — COMMENTED** [review]
Hi @Youssef1313 

I'm afraid these changes aren't required. Microsoft has a style guide, that this doc already conforms to. Changing the bolded filenames to italicised filenames would break that conformity. Thanks anyway!

**Comment by Youssef1313** [comment]
@davidbritch, The [style guide](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/contributing-guidelines/template.md#text-styling) says that file names are italics.

**Comment by davidbritch** [comment]
@Youssef1313 Reopening so I'll take another look.

**Comment by conceptdev** [comment]
Thanks for the feedback @Youssef1313. The bulk of our content came from an older publishing system and we've kept some styles (such as bolded filenames) so the Xamarin docs are all "internally consistent". We may in future look to do a bulk-update of all our content, but for now we will keep the existing formatting. We appreciate the work you put into contributing, and look forward to working with you in the future.

**Pull request closed without merging**
