### PR TITLE
Change MediaPicker macOS to limited support

### PR DESCRIPTION
**Pull request by jfversluis**
I think MediaPicker for macOS is supposed to be limited support? Since capturing an image seems not available.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@jfversluis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@jamesmontemagno Views?

**Comment by davidbritch** [comment]
@mattleibow Views?

**Comment by jamesmontemagno** [comment]
#sign-off

**Review by jamesmontemagno — APPROVED** [review]

**Review by davidbritch — APPROVED** [review]
Thanks @jfversluis

**Pull request merged**
