### PR TITLE
Minor: Fix grammatical errors in readme(s)

### PR DESCRIPTION
**Pull request by divyanshkul**
- Fixed errors in multiple docs:
       - Readme
       - Contributing Guidelines/voice-tone.md
       - android/app-fundamentals/notifications/local-notifications.md

Happy Hacktoberfest! 🎉

### CODE REVIEW

**Comment by divyanshkul** [comment]
Ping @conceptdev
Do you want me to squash the commits?

**Comment by conceptdev** [comment]
@divyanshkul you have made an edit to a section entitled **Legal notices**. If you can revert that change we can review the rest of the PR. Thanks.

**Comment by divyanshkul** [comment]
Hey @conceptdev have a look at it. Now, while I see this, I know they are not what you may say as substantial changes, but I wanted to contribute my bit.

(Also, do you want me to squash? I mean it's a pretty big repo, and I don't have a good internet. I can squash but it'd be great if you could do it from your side. :) )

**Review by jzeferino — APPROVED** [review]

**Comment by divyanshkul** [comment]
Ping @conceptdev :')
Are these okay now?

**Review by conceptdev — APPROVED** [review]

**Pull request merged**
