### PR TITLE
Update file-system-helpers.md

### PR DESCRIPTION
**Pull request by K232**
Info about change of Application ID to avoid that the whole path is stored somewhere in settings or else

### CODE REVIEW

**Comment by PRMerger20** [comment]
@K232 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@jamesmontemagno @Redth Can one of you advise if this PR is safe to merge?

**Comment by Redth** [comment]
This is indeed the behaviour (I've confirmed it).  I'm not sure there's a better directory to use for this either, unfortunately.

**Review by davidbritch — APPROVED** [review]
Thanks @K232

**Pull request merged**
