### PR TITLE
added the sender parameter for the event

### PR DESCRIPTION
**Pull request by ehsansajjad465**
The event method needs two parameters and first one is normally sender which is of type object

### CODE REVIEW

**Review by conceptdev — APPROVED** [review]
Thanks for your contribution - looks good to me, @jamesmontemagno can you confirm?

**Comment by ehsansajjad465** [comment]
> Thanks for your contribution - looks good to me, @jamesmontemagno can you confirm?

Thanks @conceptdev , just came in front of this via [a stackoverflow question](https://stackoverflow.com/questions/54626104/xamarin-essentials-no-overload-for-onmaindisplayinfochanged-matches-delegat) where the OP was getting compile time error while following the example from the docs, and it's my very first contribution to open source 👍

**Comment by conceptdev** [comment]
We appreciate you taking the time, as it helps everyone!

**Comment by jamesmontemagno** [comment]
Looks good here! Good catch

**Review by jamesmontemagno — APPROVED** [review]

**Pull request merged**
