### PR TITLE
Added missing SpecialFolder paths

### PR DESCRIPTION
**Pull request by PieEatingNinjas**
(see: [Updated SpecialFolder paths](https://github.com/MicrosoftDocs/xamarin-docs/pull/1604))
The following SpecialFolder values aren't mentioned, despite they are being mapped:
Fonts -> INTERNAL_STORAGE/.fonts
Templates -> INTERNAL_STORAGE/Templates
CommonApplicationData -> /usr/share
CommonTemplates -> /usr/share

### CODE REVIEW

**Comment by conceptdev** [comment]
Thanks for this @PieEatingNinjas - just want to validate that they work fine in code, without permissions issues, before merged. Not sure if you've already tried them all out?

**Comment by PieEatingNinjas** [comment]
The resulting list is from looping over the enum and printing out the result. 
Afaik you don’t have the permission to write to all of these locations, but I think that there are already paths in the list that aren’t allowed to write to. 
Maybe add like an ‘*’ to items in the list and add mention that for these locations you don’t have permission?

**Comment by PRMerger10** [comment]
@PieEatingNinjas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@JonDouglas Can you let me know if this is safe to merge?

**Comment by davidbritch** [comment]
@jonpryor Can you advise if this is safe to merge?

**Review by davidbritch — APPROVED** [review]
Hi @PieEatingNinjas 

Apologies for the delay in dealing with this PR.

**Comment by PRMerger6** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
