### PR TITLE
Adding survey to custom bindings pages

### PR DESCRIPTION
**Pull request by ThisIsKirsch**
This pull request is aimed at adding a custom binding survey to the relevant docs pages regarding custom bindings in Xamarin. The hope is that through this survey we will gain a better understanding of user pain points and be able to address custom binding concerns better.

### CODE REVIEW

**Comment by ThisIsKirsch** [comment]
@davidbritch Here is the pull request!

**Comment by PRMerger13** [comment]
@ThisIsKirsch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]

**Pull request merged**
