### PR TITLE
Use dotnetcli

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Youssef1313 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by conceptdev** [comment]
@Youssef1313 I haven't seen this language specification before. Because there is no preview for public PRs, can you refer me to another page where you've seen this markup? Thanks!

**Comment by Youssef1313** [comment]
@conceptdev, Example is in the .NET Core CLI docs itself. See [dotnet new](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new) for example. The support for it has been for about 2 months. See https://github.com/dotnet/docs/pull/14484

**Review by conceptdev — APPROVED** [review]
Thanks for teaching me about this.

**Comment by conceptdev** [comment]
#sign-off

**Pull request merged**
