### PR TITLE
Changed GPS package name

### LINKED ISSUE #990: Incorrect Package for FusedLocationProviderClient
The article says to install the package Xamarin.GooglePlayServices.Maps when really Xamarin.GooglePlayServices.Location is the required package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091d4a3-b105-70f5-38d2-5b2de109ed04
* Version Independent ID: 7081d0bd-9061-eda8-dac2-1f6f42bffd02
* Content: [Location Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/location)
* Content Source: [docs/android/platform/maps-and-location/location.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/maps-and-location/location.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

### PR DESCRIPTION
**Pull request by davehump**
Fixes #990

### CODE REVIEW

**Comment by PRMerger10** [comment]
@newky2k : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@JonDouglas Can you review?

**Review by JonDouglas — APPROVED** [review]

**Comment by JonDouglas** [comment]
Yep this is correct. It's found in https://www.nuget.org/packages/Xamarin.GooglePlayServices.Location/

**Review by davidbritch — APPROVED** [review]
Thanks @davehump

**Pull request merged**
