### PR TITLE
Fix the Easing parameter implicit converter

### PR DESCRIPTION
**Pull request by mshwf**
the Func parameter needs to be set explicitly

### CODE REVIEW

**Comment by PRMerger8** [comment]
@mshwf : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks @mshwf 

I modified the constructor example because it just needed casting to `Easing`.

**Comment by davidbritch** [comment]
#sign-off

**Pull request merged**
