### PR TITLE
typo: publically -> publicaly

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by alanag13** [comment]
"publicly" is actually the correct spelling for this.

**Comment by nschonni** [comment]
Grabbed it from the Oxford Dictionary common misspelling list. Did a quick search and came across this http://www.macmillandictionaryblog.com/is-there-a-case-for-publically-part-1

**Comment by alanag13** [comment]
Your link asserts that "publically" is an acceptable spelling (in addition to "publicly"). "Publically" is what is in the docs currently -- so should either be left as-is or changed to the more common "publicly", but "publicaly" (with one l) is not an accepted spelling.

**Comment by nschonni** [comment]
Thanks, I'll fix that. The original thing I based it on was https://en.oxforddictionaries.com/spelling/common-misspellings but it looks like I typo'd between the find/replace :wink:

**Pull request closed without merging**
