### PR TITLE
Update app-actions.md

### PR DESCRIPTION
**Pull request by matt-goldman**
Adds the missing intent filter which is required for this to work

### CODE REVIEW

**Comment by PRMerger12** [comment]
@matt-goldman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@jamesmontemagno Views?

**Review by jamesmontemagno — APPROVED** [review]
Good catch!

**Review by davidbritch — APPROVED** [review]
Thanks @matt-goldman

**Comment by PRMerger12** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
