### PR TITLE
chore: add Markdownlint GitHub Action

### PR DESCRIPTION
**Pull request by nschonni**
dotnet/docs is trying this out https://github.com/dotnet/docs/pull/15184

### CODE REVIEW

**Comment by conceptdev** [comment]
Thanks @nschonni - we are waiting to see how the dotnet team likes it. Appreciate the thought though!

**Comment by nschonni** [comment]
No problem, same comment as on the other PR, feel free to redo yourself

**Comment by nschonni** [comment]
FYI, @dendeli-msft not sure if this is something your group was looking at more broadly

**Comment by nschonni** [comment]
Sounds like it's working for them so far :)

**Comment by nschonni** [comment]
Updated with the latest tweaks from the dotnet/docs repo

**Comment by nschonni** [comment]
Note that this is currently failing from Markdownlint issues https://github.com/nschonni/xamarin-docs/runs/515572676?check_suite_focus=true

**Comment by davidbritch** [comment]
Hi @nschonni 

Thanks for doing this PR, and apologies for the delayed response. For the time being, for this repo, we'll continue to rely on our internal tools for ensuring markdown compliance.

Thanks again!

**Comment by nschonni** [comment]
@davidbritch currently running on live there are a bunch of issues, so I don't think your internal tooling is catching this
```
$ markdownlint "**/*.md"
docs/android/get-started/installation/android-emulator/hardware-acceleration.md:139:1 MD029/ol-prefix Ordered list item 
prefix [Expected: 1; Actual: 2; Style: 1/2/3]
docs/android/get-started/installation/android-emulator/hardware-acceleration.md:143:1 MD029/ol-prefix Ordered list item 
prefix [Expected: 2; Actual: 3; Style: 1/2/3]
docs/android/platform/androidx.md:72:1 MD029/ol-prefix Ordered list item prefix [Expected: 1; Actual: 2; Style: 1/2/3]  
docs/android/platform/androidx.md:73:1 MD029/ol-prefix Ordered list item prefix [Expected: 2; Actual: 3; Style: 1/2/3]  
docs/cross-platform/cpp/index.md:775:130 MD047/single-trailing-newline Files should end with a single newline character 
docs/cross-platform/internals/available-assemblies.md:77:427 MD047/single-trailing-newline Files should end with a single newline character
docs/cross-platform/macios/apple-account-management.md:94 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/cross-platform/macios/unified/overview.md:379 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 
1; Actual: 2]
docs/essentials/app-theme.md:43 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]      
docs/essentials/app-theme.md:52 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]      
docs/essentials/app-theme.md:57 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]      
docs/essentials/app-theme.md:70:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/essentials/app-theme.md:71:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/essentials/permissions.md:191:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/essentials/permissions.md:192:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]
docs/essentials/permissions.md:194 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]   
docs/essentials/platform-extensions.md:142:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]     
docs/essentials/platform-extensions.md:143:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]     
docs/essentials/platform-extensions.md:144:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]     
docs/essentials/platform-extensions.md:145:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]     
docs/essentials/preferences.md:75:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
docs/essentials/preferences.md:76:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
docs/essentials/preferences.md:77:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
docs/essentials/preferences.md:78:1 MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
docs/graphics-games/index.md:21 MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
docs/graphics-games/index.md:30 MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
docs/graphics-games/index.md:39 MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
docs/graphics-games/index.md:41:13 MD047/single-trailing-newline Files should end with a single newline character       
docs/ios/app-fundamentals/images-icons/app-icons.md:129:21 MD037/no-space-in-emphasis Spaces inside emphasis markers [Context: "**Info.  **"]
docs/ios/deploy-test/mtouch.md:149 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]   
docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md:28 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/ios/get-started/installation/device-provisioning/manual-provisioning.md:159 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/ios/user-interface/controls/webview.md:127:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]docs/ios/user-interface/controls/webview.md:128:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]docs/ios/user-interface/controls/webview.md:129:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]docs/ios/user-interface/controls/webview.md:156:1 MD004/ul-style Unordered list style [Expected: asterisk; Actual: dash]docs/ios/user-interface/storyboards/index.md:229:1 MD029/ol-prefix Ordered list item prefix [Expected: 1; Actual: 3; Style: 1/2/3]
docs/ios/user-interface/storyboards/index.md:233:1 MD029/ol-prefix Ordered list item prefix [Expected: 2; Actual: 4; Style: 1/2/3]
docs/ios/user-interface/storyboards/index.md:237:1 MD029/ol-prefix Ordered list item prefix [Expected: 3; Actual: 5; Style: 1/2/3]
docs/ios/user-interface/storyboards/index.md:241:1 MD029/ol-prefix Ordered list item prefix [Expected: 4; Actual: 6; Style: 1/2/3]
docs/ios/user-interface/storyboards/index.md:245:1 MD029/ol-prefix Ordered list item prefix [Expected: 5; Actual: 7; Style: 1/2/3]
docs/ios/user-interface/storyboards/index.md:249:1 MD029/ol-prefix Ordered list item prefix [Expected: 6; Actual: 8; Style: 1/2/3]
docs/tools/ci/teamcity.md:125 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
docs/tools/index.md:52 MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
docs/xamarin-forms/app-fundamentals/custom-renderer/map-pin.md:68:1 MD010/no-hard-tabs Hard tabs [Column: 1]
docs/xamarin-forms/app-fundamentals/custom-renderer/map-pin.md:69:1 MD010/no-hard-tabs Hard tabs [Column: 1]
docs/xamarin-forms/data-cloud/azure-cognitive-services/speech-recognition.md:469:161 MD047/single-trailing-newline Files should end with a single newline character
docs/xamarin-forms/deploy-test/hot-restart.md:27 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/xamarin-forms/platform/windows/default-image-directory.md:24:1 MD010/no-hard-tabs Hard tabs [Column: 1]
docs/xamarin-forms/samples/index.md:68:178 MD047/single-trailing-newline Files should end with a single newline character
docs/xamarin-forms/xaml/attached-properties.md:16 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
docs/xamarin-forms/xaml/hot-reload.md:52 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "* **Windows** [How To: Set mul..."]
```

**Pull request closed without merging**
