### PR TITLE
Added note about Api 31

### PR DESCRIPTION
**Pull request by alihamie**
Added note for Api 31 that it needs JDK 11 to work.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@alihamie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maddymontaquila — APPROVED** [review]
Thanks Ali!

**Review by davidortinau — APPROVED** [review]

**Comment by alihamie** [comment]
#signoff

**Comment by alihamie** [comment]
#sign-off

**Comment by PRMerger4** [comment]
@alihamie: I'm sorry - only the author of this article, @davidortinau, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jamesmontemagno** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@jamesmontemagno: I'm sorry - only the author of this article, @davidortinau, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
