### PR TITLE
fix: MD009/no-trailing-spaces

### PR DESCRIPTION
**Pull request by nschonni**
Automated cleanup using `markdownlint --fix  "**/*.md"`

### CODE REVIEW

**Comment by nschonni** [comment]
Doesn't touch the double trailing spaces used for newlines, just single or uneven trailing space

**Comment by conceptdev** [comment]
479 files will take a while to review! For future reference, bulk changes like this can be easier for us to process if they're done by folder/platform (eg. ios, android, xamarin-forms). Appreciate your work!

**Comment by davidbritch** [comment]
Hi @nschonni 

Apologies that this PR never got fully dealt with last year. Unfortunately, I just don't have the capacity to review 479 file changes in one go. Coupled with the number of merge conflicts that now exist, I'm going to close this PR.

**Comment by nschonni** [comment]
@davidbritch you can run this yourself locally by disabling the rule in the config and running the command in the first line

**Pull request closed without merging**
