### PR TITLE
Updated Xamarin.Essentials: File Picker

### PR DESCRIPTION
**Pull request by dimonovdd**
~~Added info about MANAGE_DOCUMENTS android permission  into Essentials File Picker~~
~~An exception occurs without this permission when using third-party file managers~~

Main pull request was changed.
Linked [Issue](https://github.com/xamarin/Essentials/issues/1444) and [Pull Request](https://github.com/xamarin/Essentials/pull/1446)

**Updated information on Android:**
`The URI of the resulting file may not be persisted between reboots`

### CODE REVIEW

**Comment by PRMerger16** [comment]
@dimonovdd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@jamesmontemagno Views?

**Review by jamesmontemagno — APPROVED** [review]

**Comment by dimonovdd** [comment]
@davidbritch 
I think we should not close this pull request while the [main issue](https://github.com/xamarin/Essentials/issues/1444) is open.

**Comment by davidbritch** [comment]
@dimonovdd Give me a nudge when it's ok to merge.

**Comment by PRMerger12** [comment]
@dimonovdd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mattleibow — APPROVED** [review]
I have merged https://github.com/xamarin/Essentials/pull/1446

**Comment by dimonovdd** [comment]
@davidbritch 

> Give me a nudge when it's ok to merge.

https://github.com/xamarin/Essentials/releases/tag/1.6.0-pre3

**Comment by PRMerger12** [comment]
@dimonovdd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jamesmontemagno — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Review by davidbritch — APPROVED** [review]
Thanks @dimonovdd

**Comment by PRMerger17** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
