### PR TITLE
Update out-of-process-services.md

### PR DESCRIPTION
**Pull request by bkokash**
IServiceConnection does not have the Messenger property, as requested in the next step: serviceConnection.Messenger.Send(msg); this will confuse the reader, so it should be either changed to TimestampServiceConnection or to var.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@bkokash : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@conceptdev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by conceptdev — APPROVED** [review]
Thanks again for these fixes, I chose `var`

**Comment by conceptdev** [comment]
#sign-off

**Pull request merged**
