### PR TITLE
Update create-web-service-classes.md

### PR DESCRIPTION
**Pull request by keithnicholson**
Without the UserAgent I was receiving a 403 error.

### CODE REVIEW

**Comment by davidbritch** [comment]
Hi @keithnicholson 

Was this on Windows?

**Comment by davidbritch** [comment]
Hi @keithnicholson 

I've tried the sample that the tutorial links to, from both VS2019 and VSMac, and it runs on both iOS and Android without requiring any modification (no need to set the user agent etc.).

**Comment by keithnicholson** [comment]
@davidbritch Thank you for looking into this.

My addition of code was necessary for the UWP project.  I commented the two lines of code out and ran it in the Android project.  It ran just fine like you experienced.

Can you try executing the code as UWP and see if you see the 403 error in the response of the _client.GetAsync(uri)?

**Comment by davidbritch** [comment]
Hi @keithnicholson 

Agreed that this is a problem on UWP, and that you've identified the solution. I've already updated the sample. I'll get the doc updated.

**Review by davidbritch — APPROVED** [review]
Thanks @keithnicholson

**Pull request merged**
