### PR TITLE
Correct many spelling, grammar and typing errors

### PR DESCRIPTION
**Pull request by Devvox93**
While reading this article I saw not just a few errors and it started to annoy me. I was also curious in contributing to the docs and combined those two in these edits :)

### CODE REVIEW

**Review by topgenorth — APPROVED** [review]
Thanks for taking the time to fix up the spelling errors (or regional difference in spelling)!

**Comment by topgenorth** [comment]
@Devvox93 Please note that we can't merge this until you sign the [Contributor License Agreement](https://cla.opensource.microsoft.com/MicrosoftDocs/xamarin-docs?pullRequest=195) . 😃

**Comment by Devvox93** [comment]
Reading it as we "speak" ;)

**Comment by Devvox93** [comment]
@topgenorth Thanks for the label! :) Also, I am the only one seeing the details (like name and email) of my signed agreement in the "all checks" session, right?

**Comment by topgenorth** [comment]
I believe the details of your CLA agreement are private.

**Pull request merged**
