### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Update to reflect latest stable version for Xamarin Profiler on macOS.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@robertleeblairjr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by conceptdev — APPROVED** [review]
Thanks! Looks like someone forgot to update this 😬

**Comment by conceptdev** [comment]
@sign-off

**Comment by robertleeblairjr** [comment]
> Thanks! Looks like someone forgot to update this 😬

Appreciate it. I'm searching for the release notes page in the repo. But, it looks like it's been removed or has a dead link. Has it moved or any way to get that revised to 1.6.13-11.

[https://developer.xamarin.com/releases/profiler/](url)

Edit: I opened a PR #2589

**Pull request merged**
