### PR TITLE
Issue#498

### PR DESCRIPTION
**Pull request by CliffAgius**
This is changes to the docs for this issue so that they now match the changes made for VS_Win 15.8.0

### CODE REVIEW

**Comment by davidbritch** [comment]
Thanks for the PR. We'll leave it here until 15.8 becomes a stable release.

**Review by jzeferino — APPROVED** [review]
LGTM.

**Comment by conceptdev** [comment]
Visual Studio 2017 version 15.8 is now stable, but Visual Studio for Mac has a slight delay. Because this PR covers both, we'll wait until the Mac update is also released.

**Review by davidbritch — APPROVED** [review]
Thanks for the PR @CliffAgius

**Pull request merged**
