### PR TITLE
Added checkbox link

### PR DESCRIPTION
**Pull request by iamlawrencev**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@iamlawrencev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — COMMENTED** [review]
Hi @iamlawrencev 

If you look at the Xamarin.Forms API docs (https://docs.microsoft.com/dotnet/api/xamarin.forms?view=xamarin-forms) you'll see that there isn't an API doc for `CheckBox`. Therefore, the `xref` you've added for `CheckBox` will cause a docs build error, as it won't resolve.

So, unfortunately, I'll have to close this PR.

**Comment by iamlawrencev** [comment]
Hi @davidbritch,

I see that there is an API doc for `CheckBox` now. Can this be accepted now?

**Comment by davidbritch** [comment]
Hi @iamlawrencev 

Yes, it can be accepted. However, I can't reopen this PR as it says the repository that submitted this pull request has been deleted.

**Pull request closed without merging**
