### PR TITLE
Update coreml.md

### PR DESCRIPTION
**Pull request by zerotosingularity**
Changed the build action to "CoreMLModel".

### CODE REVIEW

**Comment by jzeferino** [comment]
I was [searching](https://github.com/xamarin/xamarin-macios/search?utf8=%E2%9C%93&q=CoreMLModel&type=) for the `CoreMLModel` in the xamarin.macios repo and didn't find the task there. Were is it documented? @zerotosingularity

**Comment by zerotosingularity** [comment]
I encountered it while playing around with the MarsHabitatPricePredictor sample [from the website](https://developer.xamarin.com/samples/monotouch/ios11/CoreML/).

In that example, the BuildAction is set to "CoreMLModel" as you can see in the attached screenshot. 
screen shot 2018-05-25 at 11 25 01

I just ran the sample with the BuildAction set to "BundleResource" and that seems to work too. Is there a difference between the two?

**Review by jzeferino — APPROVED** [review]
LGTM.

**Comment by conceptdev** [comment]
@zerotosingularity @jzeferino I *think* when we first released CoreML support, we used the `BundleResource` setting, but the team subsequently added the `CoreMLModel` option. Verifying this before merging the PR, but it looks good to me, thanks!

**Review by bradumbaugh — DISMISSED** [review]

**Comment by bradumbaugh** [comment]
Hi @zerotosingularity and @jzeferino – thanks for calling this out! There were a few other changes to be made to this, and I've gone ahead and made them in another PR, so I'm going to close this out. Really appreciate the help with this – fixes should be published soon.

**Comment by jzeferino** [comment]
@bradumbaugh please reference that PR here so we can take a look after.

**Review by bradumbaugh — APPROVED** [review]

**Comment by bradumbaugh** [comment]
@zerotosingularity On second thought, I made a minor update to this PR and will merge it. Xamarin can now work with .mlmodel files directly (it's no longer necessary to compile to .mlmodelc manually).

Thanks for the update, @zerotosingularity – appreciate your contribution. I have a few other fixes for this doc, but I'll put them in a separate PR.

**Pull request merged**
