### PR TITLE
Update web-authenticator.md

### PR DESCRIPTION
**Pull request by abubakr-taha**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@abubakrtaha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidbritch** [comment]
@jamesmontemagno Views?

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
I think this is fine to go.
#sign-off

**Comment by PRMerger15** [comment]
@jamesmontemagno: I'm sorry - only the author of this article, @redth, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by Redth — APPROVED** [review]

**Review by davidbritch — APPROVED** [review]
Thanks @abubakrtaha

**Pull request merged**
