### PR TITLE
Update partners with XAM Consulting

### PR DESCRIPTION
**Pull request by rid00z**
XAM Consulting are a Microsoft Silver Partner for Application Development with a focus on Xamarin, partner id5046093.

### CODE REVIEW

**Comment by conceptdev** [comment]
Hey @rid00z we need confirmation from your partner manager to accept this PR (usually they request the updates). If you can reach out to your contact and get them to ping me, that'd be great.

**Comment by dannyjr894** [comment]
Some one else been playing with my phone trying to make it hard to see content

**Comment by dannyjr894** [comment]
Remove the do not remove tag

**Comment by dannyjr894** [comment]
Then merge

**Comment by dannyjr894** [comment]
Remove the do not remove tag them merge

**Comment by dannyjr894** [comment]
Remove the tag

**Comment by dannyjr894** [comment]
What partner I should not have one

**Comment by dannyjr894** [comment]
And my partner what do u mean by that how does that happen

**Comment by dannyjr894** [comment]
Help me under stand this

**Comment by dannyjr894** [comment]
I don't have a partner so @rid00z is hacked my account

**Comment by dannyjr894** [comment]
Undo everything I asked cause it's not me

**Comment by dannyjr894** [comment]
I don't even kw what this site does

**Comment by dannyjr894** [comment]
I don't even kw what this site does don't change a thing until they verify that it's ok with me

**Comment by dannyjr894** [comment]
Merge

**Comment by dannyjr894** [comment]
Hey some one else is telling you to change I did not  verify call  me or  something

**Review by conceptdev — APPROVED** [review]
Partner verified internally

**Pull request merged**
