### PR TITLE
Add missing void and semi-colon.

### PR DESCRIPTION
**Pull request by LuvForAirplanes**
Add void to OnResume (line 115), add void to OnPause (line 122) and add semi-colon on line 110.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@LuvForAirplanes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by conceptdev — APPROVED** [review]
Thanks for fixing!

**Comment by conceptdev** [comment]
#sign-off

**Comment by LuvForAirplanes** [comment]
Sure. Thanks for your review.

**Pull request merged**
