### PR TITLE
Corrected sample code

### PR DESCRIPTION
**Pull request by goh-chunlin**
Corrected the following problems:
1. The parameter `options` in the method `PickAndShow` is not used at all in the method;
2. Not all code paths of `PickAndShow` return a value.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@goh-chunlin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jamesmontemagno — APPROVED** [review]
Thank you!

**Comment by jamesmontemagno** [comment]
#sign-off

**Review by davidbritch — APPROVED** [review]
Thanks @goh-chunlin

**Pull request merged**
