### PR TITLE
Some Docs had wrong API in description

### PR DESCRIPTION
**Pull request by jfversluis**
Seems like a couple of copy -> paste errors.

Sorry for the email/notification storm 😬

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jfversluis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@jfversluis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@jfversluis : Thanks for your contribution! The author(s) have been notified to review your proposed change. @dimonovdd

**Review by davidbritch — APPROVED** [review]
Thanks @jfversluis

**Pull request merged**
