### PR TITLE
Update navigation.md

### PR DESCRIPTION
**Pull request by Nerves82**
Adding notes to the "Pass Data" and "Relative routes" section noting that relative routes do not support passing data.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Nerves82 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Nerves82** [comment]
https://stackoverflow.com/questions/62586261/adding-a-query-to-gotoasync-uri-navigation-in-xamarin-forms-shell-causes-it-to-s/62587419#62587419

**Comment by davidbritch** [comment]
@PureWeen Can you advise if this PR is correct?

**Comment by PureWeen** [comment]
@davidbritch 
This is a bug if this is true

I haven't seen anyone having issue with this behavior
I added a comment to the issue here

https://github.com/xamarin/Xamarin.Forms/issues/11220#issuecomment-659532021

**Comment by davidbritch** [comment]
Thanks for the PR. However, I'll close it as passing data to relative routes has been supported since 4.7.

**Pull request closed without merging**
