### PR TITLE
Give guidance on the version of essentials to use

### PR DESCRIPTION
**Pull request by DonGlover**
The code snippet requires version 1.6 or later (currently in preview)

### CODE REVIEW

**Comment by PRMerger20** [comment]
@DonGlover : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@davidbritch : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidbritch — APPROVED** [review]
Thanks @DonGlover

**Pull request merged**
